name: "Custom OLED Display"
description: "Display hostname, ip, uptime"
version: "0.0.3"
slug: "oled_display"
startup: services
boot: manual
hassio_api: true
init: false
auth_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - media:rw
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-2
  - /dev/i2c-3
  - /dev/i2c-4
  - /dev/i2c-5
  - /dev/i2c-6
  - /dev/i2c-7
  - /dev/i2c-8
  - /dev/i2c-9
  - /dev/i2c-10
  - /dev/i2c-11
  - /dev/i2c-12
  - /dev/i2c-13
  - /dev/i2c-14
  - /dev/i2c-15
  - /dev/i2c-16
  - /dev/i2c-17
  - /dev/i2c-18
  - /dev/i2c-19
  - /dev/i2c-20
options:
  Show_Static_Screen: false
  Show_Welcome_Screen: false
  Show_Splash_Screen: false
  Show_Network_Screen: false
  Show_CPU_Screen: false
  Show_Memory_Screen: false
  Show_Storage_Screen: false
  Show_Summary_Screen: true
  Summary_Screen_Text: "blah"
  Default_Duration: 10
  DateTime_Format: "%d/%m/%Y %H:%M:%S"
  Summary_Screen_Text_NoScroll: true
  Rotate: 0

  Debug_Mode: false
  I2C_bus: 1
  Screenshot: ''

schema:
  Show_Static_Screen: bool
  Show_Welcome_Screen: bool
  Show_Splash_Screen: bool
  Show_Network_Screen: bool
  Show_CPU_Screen: bool
  Show_Memory_Screen: bool
  Show_Storage_Screen: bool
  Show_Summary_Screen: bool

  Welcome_Screen_Text: "str?"
  Static_Screen_Text: "str?"
  Graceful_Exit_Text: "str?"
 
  Default_Duration: int
  Scroll_Amplitude: "int?"
  DateTime_Format: "str?"
  Static_Screen_Text_NoScroll: bool
  Temperature_Unit: "list(C|F)?"
  Rotate: "int?"

  Welcome_Screen_Duration: "int?"
  Welcome_Screen_Limit: "int?"

  Splash_Screen_Duration: "int?"
  Splash_Screen_Limit: "int?"

  Network_Screen_Duration: "int?"
  Network_Screen_Limit: "int?"

  CPU_Screen_Duration: "int?"
  CPU_Screen_Limit: "int?"

  Memory_Screen_Duration: "int?"
  Memory_Screen_Limit: "int?"

  Storage_Screen_Duration: "int?"
  Storage_Screen_Limit: "int?"

  Summary_Screen_Duration: "int?"
  Summary_Screen_Limit: "int?"
  Summary_Screen_Text_NoScroll: bool
  Summary_Screen_Text: "str?"



  Debug_Mode: bool
  I2C_bus: "int(0,20)"
  Screenshot: "list(|/media)"
